name: Build and Deploy code

on:
    push:
        branches: ["main"]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v3
            - name: say hi to Aslam
              run: echo "hi Aslam"

